import type{Account,CreditCard,Transaction,TransactionStatus,TransactionType}from"../types/entities";import{assertCents,assertNonNegativeCents}from"../money/cents";import{assertFinancialDate}from"../date/financial-date";
export type FinancialData={accounts:readonly Account[];cards?:readonly CreditCard[];transactions:readonly Transaction[]};
const real=(s:TransactionStatus)=>s==="PAID"||s==="RECEIVED";
const hasAccount=(as:readonly Account[],id:string)=>as.some(a=>a.id===id);
const hasCard=(cs:readonly CreditCard[],id:string)=>cs.some(c=>c.id===id);
export function validateTransaction(tx:Transaction,data:FinancialData):void{if(!tx.id)throw new Error("Transaction id is required");assertFinancialDate(tx.date);assertNonNegativeCents(tx.amountCents);if(tx.status==="CANCELLED")return;if((tx.type==="INCOME"||tx.type==="EXPENSE")&&tx.accountId&&!hasAccount(data.accounts,tx.accountId))throw new Error("Invalid accountId");if(tx.type==="INCOME"||tx.type==="EXPENSE"){if(tx.type==="EXPENSE"&&tx.creditCardId){if(!hasCard(data.cards??[],tx.creditCardId))throw new Error("Invalid creditCardId");if(tx.accountId)throw new Error("Card expense cannot also have accountId")}else if(!tx.accountId||!hasAccount(data.accounts,tx.accountId))throw new Error("Valid accountId is required")}if(tx.type==="TRANSFER"){if(!tx.accountId||!hasAccount(data.accounts,tx.accountId))throw new Error("Valid source accountId is required");if(!tx.destinationAccountId||!hasAccount(data.accounts,tx.destinationAccountId))throw new Error("Valid destination accountId is required");if(tx.accountId===tx.destinationAccountId)throw new Error("Transfer accounts must be different")}if(tx.type==="CARD_PAYMENT"){if(!tx.accountId||!hasAccount(data.accounts,tx.accountId))throw new Error("Valid payment accountId is required");if(!tx.creditCardId||!hasCard(data.cards??[],tx.creditCardId))throw new Error("Valid creditCardId is required")}if(tx.type!=="EXPENSE"&&tx.creditCardId)throw new Error("Only card expenses may reference a credit card")}
export function validateAllTransactions(data:FinancialData):void{for(const tx of data.transactions)validateTransaction(tx,data)}
function apply(tx:Transaction,id:string,b:number):number{if(tx.type==="INCOME"&&tx.accountId===id)return b+tx.amountCents;if(tx.type==="EXPENSE"&&tx.accountId===id)return b-tx.amountCents;if(tx.type==="TRANSFER"){if(tx.accountId===id)b-=tx.amountCents;if(tx.destinationAccountId===id)b+=tx.amountCents}if(tx.type==="CARD_PAYMENT"&&tx.accountId===id)b-=tx.amountCents;return b}
export function calculateAccountBalance(accountId:string,data:FinancialData):number{const a=data.accounts.find(x=>x.id===accountId);if(!a)throw new Error("Unknown accountId");validateAllTransactions(data);let b=a.openingBalanceCents;for(const tx of data.transactions)if(real(tx.status))b=apply(tx,accountId,b);assertCents(b,"accountBalance");return b}
export function calculateProjectedAccountBalance(accountId:string,data:FinancialData):number{const a=data.accounts.find(x=>x.id===accountId);if(!a)throw new Error("Unknown accountId");validateAllTransactions(data);let b=a.openingBalanceCents;for(const tx of data.transactions)if(tx.status!=="CANCELLED")b=apply(tx,accountId,b);assertCents(b,"projectedAccountBalance");return b}
export function calculateTotalRealBalance(data:FinancialData):number{return data.accounts.filter(a=>a.active).reduce((s,a)=>s+calculateAccountBalance(a.id,data),0)}
export function transactionAffectsCashBalance(type:TransactionType):boolean{return type!=="EXPENSE"||type==="EXPENSE"}