import{describe,expect,it}from"vitest";import{calculateAccountBalance,calculateProjectedAccountBalance,calculateTotalRealBalance,validateAccountUpdate,validateTransaction}from"./financial-engine";import type{Account,CreditCard,Transaction}from"../types/entities";
const accounts:Account[]=[{id:"a1",name:"Banco",type:"CHECKING",openingBalanceCents:100000,active:true},{id:"a2",name:"Poupança",type:"SAVINGS",openingBalanceCents:50000,active:true}];const card:CreditCard={id:"c1",name:"Cartão",accountId:"a1",creditLimitCents:500000,closingDay:10,dueDay:20,active:true};
describe("account opening balance updates",()=>{it("rejects changing opening balance after account movements",()=>{const previous=accounts[0];const next={...previous,openingBalanceCents:120000};const transactions:Transaction[]=[{id:"opening-history",date:"2026-09-01",type:"INCOME",status:"RECEIVED",amountCents:20000,description:"Salário",accountId:previous.id}];expect(()=>validateAccountUpdate(previous,next,transactions)).toThrow("O saldo inicial não pode ser alterado após haver movimentações na conta.")});it("allows changing opening balance when there is no non-cancelled account movement",()=>{const previous=accounts[0];const next={...previous,openingBalanceCents:120000};const transactions:Transaction[]=[{id:"cancelled-history",date:"2026-09-01",type:"EXPENSE",status:"CANCELLED",amountCents:20000,description:"Cancelado",accountId:previous.id}];expect(()=>validateAccountUpdate(previous,next,transactions)).not.toThrow()});});
describe("financial engine",()=>{it("calculates cash",()=>{const t:Transaction[]=[{id:"1",date:"2026-09-01",type:"INCOME",status:"RECEIVED",amountCents:200000,description:"Salário",accountId:"a1"},{id:"2",date:"2026-09-02",type:"EXPENSE",status:"PAID",amountCents:38750,description:"Compra",accountId:"a1"}];expect(calculateAccountBalance("a1",{accounts,transactions:t})).toBe(261250)});it("card purchase does not hit bank",()=>{const t:Transaction[]=[{id:"1",date:"2026-09-02",type:"EXPENSE",status:"PAID",amountCents:10000,description:"Pix",accountId:"a1"},{id:"2",date:"2026-09-03",type:"EXPENSE",status:"PAID",amountCents:50000,description:"Cartão",creditCardId:"c1"}];expect(calculateAccountBalance("a1",{accounts,cards:[card],transactions:t})).toBe(90000)});it("card payment debits bank without double-counting the card purchase",()=>{const t:Transaction[]=[{id:"1",date:"2026-09-03",type:"EXPENSE",status:"PAID",amountCents:50000,description:"Compra no cartão",creditCardId:"c1"},{id:"2",date:"2026-09-20",type:"CARD_PAYMENT",status:"PAID",amountCents:50000,description:"Pagamento da fatura",accountId:"a1",creditCardId:"c1"}];expect(calculateAccountBalance("a1",{accounts, cards:[card],transactions:t})).toBe(50000);expect(calculateTotalRealBalance({accounts, cards:[card],transactions:t})).toBe(100000)});it("pending card payment affects projected cash but not realized cash",()=>{const t:Transaction[]=[{id:"1",date:"2026-09-03",type:"EXPENSE",status:"PAID",amountCents:50000,description:"Compra no cartão",creditCardId:"c1"},{id:"2",date:"2026-09-15",type:"CARD_PAYMENT",status:"PENDING",amountCents:20000,description:"Pagamento agendado",accountId:"a1",creditCardId:"c1"}];expect(calculateAccountBalance("a1",{accounts,cards:[card],transactions:t})).toBe(100000);expect(calculateProjectedAccountBalance("a1",{accounts,cards:[card],transactions:t})).toBe(80000)});it("transfer preserves total",()=>{const t:Transaction[]=[{id:"1",date:"2026-09-05",type:"TRANSFER",status:"PAID",amountCents:20000,description:"Reserva",accountId:"a1",destinationAccountId:"a2"}];expect(calculateAccountBalance("a1",{accounts,transactions:t})).toBe(80000);expect(calculateAccountBalance("a2",{accounts,transactions:t})).toBe(70000);expect(calculateTotalRealBalance({accounts,transactions:t})).toBe(150000)});it("planned is projected only",()=>{const t:Transaction[]=[{id:"1",date:"2026-09-20",type:"EXPENSE",status:"PLANNED",amountCents:10000,description:"Conta",accountId:"a1"}];expect(calculateAccountBalance("a1",{accounts,transactions:t})).toBe(100000);expect(calculateProjectedAccountBalance("a1",{accounts,transactions:t})).toBe(90000)});it("rejects invalid relation",()=>{const t:Transaction={id:"1",date:"2026-09-01",type:"INCOME",status:"RECEIVED",amountCents:100,description:"x",accountId:"bad"};expect(()=>validateTransaction(t,{accounts,transactions:[]})).toThrow();expect(()=>calculateAccountBalance("bad",{accounts,transactions:[]})).toThrow()})})
describe("card payment account linkage",()=>{it("rejects payment from an account different from the card linked account",()=>{const tx:Transaction={id:"payment-wrong-account",date:"2026-09-20",type:"CARD_PAYMENT",status:"PAID",amountCents:50000,description:"Pagamento da fatura",accountId:"a2",creditCardId:"c1"};expect(()=>validateTransaction(tx,{accounts,cards:[card],transactions:[]})).toThrow("Card payment must use the card linked payment account")});it("accepts payment from the card linked account",()=>{const tx:Transaction={id:"payment-right-account",date:"2026-09-20",type:"CARD_PAYMENT",status:"PAID",amountCents:50000,description:"Pagamento da fatura",accountId:"a1",creditCardId:"c1"};expect(()=>validateTransaction(tx,{accounts,cards:[card],transactions:[]})).not.toThrow()})})


describe("regressões de integridade financeira",()=>{
 it("ignora lançamentos cancelados no saldo real e no projetado",()=>{
  const t:Transaction[]=[{id:"cancelled",date:"2026-09-02",type:"EXPENSE",status:"CANCELLED",amountCents:25000,description:"Cancelado",accountId:"a1"}];
  expect(calculateAccountBalance("a1",{accounts,transactions:t})).toBe(100000);
  expect(calculateProjectedAccountBalance("a1",{accounts,transactions:t})).toBe(100000);
 });
 it("mantém transferência pendente fora do saldo real, mas dentro do projetado",()=>{
  const t:Transaction[]=[{id:"transfer",date:"2026-09-15",type:"TRANSFER",status:"PENDING",amountCents:20000,description:"Reserva futura",accountId:"a1",destinationAccountId:"a2"}];
  expect(calculateAccountBalance("a1",{accounts,transactions:t})).toBe(100000);
  expect(calculateAccountBalance("a2",{accounts,transactions:t})).toBe(50000);
  expect(calculateProjectedAccountBalance("a1",{accounts,transactions:t})).toBe(80000);
  expect(calculateProjectedAccountBalance("a2",{accounts,transactions:t})).toBe(70000);
 });
 it("não conta pagamento de cartão cancelado como saída bancária",()=>{
  const t:Transaction[]=[{id:"payment",date:"2026-09-20",type:"CARD_PAYMENT",status:"CANCELLED",amountCents:30000,description:"Pagamento cancelado",accountId:"a1",creditCardId:"c1"}];
  expect(calculateAccountBalance("a1",{accounts,cards:[card],transactions:t})).toBe(100000);
  expect(calculateProjectedAccountBalance("a1",{accounts,cards:[card],transactions:t})).toBe(100000);
 });
});
