import { StrictMode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
import type { Account, Transaction, TransactionStatus, TransactionType } from "./domain/types/entities";
import type { EntityCollection } from "./infrastructure/persistence/repository";
import { IndexedDbFinanceRepository } from "./infrastructure/persistence/indexeddb";
import { calculateAccountBalance, calculateProjectedAccountBalance, calculateTotalRealBalance } from "./domain/transactions/financial-engine";
import { emptyEntityCollection } from "./infrastructure/persistence/backup";
import { isSupabaseConfigured } from "./infrastructure/supabase/client";
import { createFamily, joinFamily, listMyFamilies } from "./infrastructure/supabase/family";
import { getAuthState, signInWithEmail, signOut, signUpWithEmail } from "./infrastructure/supabase/auth";
import { pushFromLocalFirst } from "./infrastructure/supabase/sync-coordinator";

const repo=new IndexedDbFinanceRepository();
const money=(c:number)=>(c/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const today=()=>new Date().toLocaleDateString("en-CA");
const id=()=>crypto.randomUUID();
type Page="dashboard"|"contas"|"lancamentos"|"cartoes";
const nav:[Page,string,string][]=[["dashboard","Início","⌂"],["contas","Contas","▣"],["lancamentos","Lançamentos","＋"],["cartoes","Cartões","▤"]];

async function load():Promise<EntityCollection>{const [people,categories,accounts,cards,transactions,installmentGroups]=await Promise.all([repo.list("people"),repo.list("categories"),repo.list("accounts"),repo.list("cards"),repo.list("transactions"),repo.list("installmentGroups")]);return{people,categories,accounts,cards,transactions,installmentGroups};}

function App(){
 const [ready,setReady]=useState(false),[user,setUser]=useState<string|null>(null),[data,setData]=useState<EntityCollection>(emptyEntityCollection()),[page,setPage]=useState<Page>("dashboard"),[family,setFamily]=useState(localStorage.getItem("cff_family_id")),[version,setVersion]=useState(Number(localStorage.getItem("cff_remote_version")||0)),[syncing,setSyncing]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{load().then(setData).finally(()=>setReady(true));},[]);
 useEffect(()=>{if(!isSupabaseConfigured){setReady(true);return;}getAuthState().then(s=>setUser(s.user?.id??null)).catch(()=>setUser(null));},[]);
 useEffect(()=>{if(!isSupabaseConfigured||!user||family)return;listMyFamilies().then(fs=>fs[0]&&setFamily(fs[0].id)).catch(()=>{});},[user,family]);
 const save=async(next:EntityCollection)=>{setData(next);await repo.replaceAll(next);if(isSupabaseConfigured&&family){setSyncing(true);try{const r=await pushFromLocalFirst(family,next,version);if(r.kind==="pushed"){setVersion(r.version);localStorage.setItem("cff_remote_version",String(r.version));}if(r.kind==="conflict")setNotice("Existe uma alteração remota. A mesclagem automática foi evitada para proteger os dados.");}catch(e){setNotice(e instanceof Error?e.message:"Falha ao sincronizar.");}finally{setSyncing(false);}}};
 if(!ready)return <div className="splash">Carregando seu financeiro…</div>;
 if(isSupabaseConfigured&&!user)return <Auth onLogin={setUser}/>;
 if(isSupabaseConfigured&&!family)return <Family onSelect={f=>{setFamily(f);localStorage.setItem("cff_family_id",f)}} onLogout={async()=>{await signOut();setUser(null)}}/>;
 const balance=calculateTotalRealBalance({accounts:data.accounts.filter(a=>a.active),cards:data.cards,transactions:data.transactions});
 return <div className="app-shell"><header className="topbar"><div><span className="eyebrow">CONTROLE FINANCEIRO</span><h1>Familiar</h1></div><span className={syncing?"sync":"sync ok"}>{syncing?"Sincronizando…":isSupabaseConfigured?"Sincronizado":"Local"}</span></header>{notice&&<button className="notice" onClick={()=>setNotice("")}>{notice}</button>}<main className="content">{page==="dashboard"&&<Dashboard data={data} balance={balance}/>} {page==="contas"&&<Accounts data={data} save={save}/>} {page==="lancamentos"&&<Transactions data={data} save={save}/>} {page==="cartoes"&&<Cards data={data} save={save}/>}</main><nav className="bottom-nav">{nav.map(([p,l,i])=><button key={p} className={page===p?"active":""} onClick={()=>setPage(p)}><b>{i}</b><span>{l}</span></button>)}</nav></div>;
}

function Dashboard({data,balance}:{data:EntityCollection;balance:number}){
 const projected=data.accounts.filter(a=>a.active).reduce((s,a)=>s+calculateProjectedAccountBalance(a.id,{accounts:data.accounts,cards:data.cards,transactions:data.transactions}),0);
 const key=today().slice(0,7),tx=data.transactions.filter(t=>t.date.startsWith(key)&&t.status!=="CANCELLED"),income=tx.filter(t=>t.type==="INCOME").reduce((s,t)=>s+t.amountCents,0),expense=tx.filter(t=>t.type==="EXPENSE").reduce((s,t)=>s+t.amountCents,0);
 return <><section className="hero"><span>Saldo total real</span><strong>{money(balance)}</strong><div><span>Projetado</span><b>{money(projected)}</b></div></section><div className="section-title"><span className="eyebrow">VISÃO DO MÊS</span><h2>{new Date().toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</h2></div><div className="metrics"><Metric label="Entradas" value={money(income)}/><Metric label="Despesas" value={money(expense)}/></div><section className="card"><h3>Contas ativas</h3>{data.accounts.filter(a=>a.active).map(a=><AccountRow key={a.id} account={a} data={data}/>)}{!data.accounts.some(a=>a.active)&&<Empty text="Cadastre sua primeira conta."/>}</section></>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function AccountRow({account,data}:{account:Account;data:EntityCollection}){return <div className="row"><div><strong>{account.name}</strong><small>{account.type}</small></div><strong>{money(calculateAccountBalance(account.id,{accounts:data.accounts,cards:data.cards,transactions:data.transactions}))}</strong></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}

function Accounts({data,save}:{data:EntityCollection;save:(d:EntityCollection)=>Promise<void>}){
 const [name,setName]=useState(""),[opening,setOpening]=useState(""),[type,setType]=useState<Account["type"]>("CHECKING");
 const add=async()=>{const cents=Math.round(Number(opening.replace(",","."))*100);if(!name.trim()||!Number.isSafeInteger(cents))return;await save({...data,accounts:[...data.accounts,{id:id(),name:name.trim(),type,openingBalanceCents:cents,active:true}]});setName("");setOpening("");};
 return <><Title label="PATRIMÔNIO" title="Contas"/><section className="card form"><input placeholder="Nome da conta" value={name} onChange={e=>setName(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value as Account["type"])}><option value="CHECKING">Conta corrente</option><option value="SAVINGS">Poupança</option><option value="DIGITAL">Conta digital</option><option value="CASH">Dinheiro</option><option value="INVESTMENT">Investimentos</option></select><input inputMode="decimal" placeholder="Saldo inicial (R$)" value={opening} onChange={e=>setOpening(e.target.value)}/><button className="primary" onClick={add}>Adicionar conta</button></section><section className="card">{data.accounts.filter(a=>a.active).map(a=><AccountRow key={a.id} account={a} data={data}/>)}</section></>;
}
function Transactions({data,save}:{data:EntityCollection;save:(d:EntityCollection)=>Promise<void>}){
 const [description,setDescription]=useState(""),[amount,setAmount]=useState(""),[type,setType]=useState<TransactionType>("EXPENSE"),[status,setStatus]=useState<TransactionStatus>("PAID"),[accountId,setAccountId]=useState(""),[date,setDate]=useState(today());
 const add=async()=>{const cents=Math.round(Number(amount.replace(",","."))*100);if(!description.trim()||!accountId||!Number.isSafeInteger(cents)||cents<=0)return;const tx:Transaction={id:id(),date,type,status,amountCents:cents,description:description.trim(),accountId};await save({...data,transactions:[...data.transactions,tx]});setDescription("");setAmount("");};
 return <><Title label="MOVIMENTAÇÕES" title="Lançamentos"/><section className="card form"><input placeholder="Descrição" value={description} onChange={e=>setDescription(e.target.value)}/><div className="two"><select value={type} onChange={e=>setType(e.target.value as TransactionType)}><option value="EXPENSE">Despesa</option><option value="INCOME">Receita</option></select><select value={status} onChange={e=>setStatus(e.target.value as TransactionStatus)}><option value="PAID">Pago</option><option value="RECEIVED">Recebido</option><option value="PENDING">Pendente</option><option value="PLANNED">Planejado</option></select></div><input inputMode="decimal" placeholder="Valor (R$)" value={amount} onChange={e=>setAmount(e.target.value)}/><select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Conta</option>{data.accounts.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="primary" onClick={add}>Salvar lançamento</button></section><section className="card">{[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)).map(t=><div className="row" key={t.id}><div><strong>{t.description}</strong><small>{t.date} · {t.status}</small></div><strong className={t.type==="EXPENSE"?"negative":"positive"}>{t.type==="EXPENSE"?"−":"+"}{money(t.amountCents)}</strong></div>)}</section></>;
}
function Cards({data,save}:{data:EntityCollection;save:(d:EntityCollection)=>Promise<void>}){
 const [name,setName]=useState(""),[limit,setLimit]=useState(""),[accountId,setAccountId]=useState(""),[closing,setClosing]=useState("10"),[due,setDue]=useState("15");
 const add=async()=>{const cents=Math.round(Number(limit.replace(",","."))*100),c=Number(closing),d=Number(due);if(!name.trim()||!accountId||!Number.isSafeInteger(cents)||c<1||c>31||d<1||d>31)return;await save({...data,cards:[...data.cards,{id:id(),name:name.trim(),accountId,creditLimitCents:cents,closingDay:c,dueDay:d,active:true}]});setName("");setLimit("");};
 return <><Title label="CRÉDITO" title="Cartões"/><section className="card form"><input placeholder="Nome do cartão" value={name} onChange={e=>setName(e.target.value)}/><input inputMode="decimal" placeholder="Limite (R$)" value={limit} onChange={e=>setLimit(e.target.value)}/><select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Conta para pagar fatura</option>{data.accounts.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><div className="two"><input type="number" min="1" max="31" value={closing} onChange={e=>setClosing(e.target.value)}/><input type="number" min="1" max="31" value={due} onChange={e=>setDue(e.target.value)}/></div><button className="primary" onClick={add}>Adicionar cartão</button></section><section className="card">{data.cards.filter(c=>c.active).map(c=><div className="row" key={c.id}><div><strong>{c.name}</strong><small>Fecha {c.closingDay} · vence {c.dueDay}</small></div><strong>{money(c.creditLimitCents)}</strong></div>)}</section></>;
}
function Title({label,title}:{label:string;title:string}){return <div className="section-title"><span className="eyebrow">{label}</span><h2>{title}</h2></div>}
function Auth({onLogin}:{onLogin:(id:string)=>void}){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[signup,setSignup]=useState(false),[error,setError]=useState("");const submit=async()=>{try{setError("");const r=signup?await signUpWithEmail(email,password):await signInWithEmail(email,password);if(r.user)onLogin(r.user.id);else setError("Cadastro criado. Confirme o e-mail antes de entrar.");}catch(e){setError(e instanceof Error?e.message:"Não foi possível autenticar.");}};return <div className="auth"><section className="auth-card"><span className="eyebrow">CONTROLE FINANCEIRO FAMILIAR</span><h1>{signup?"Criar acesso":"Entrar"}</h1><p>Seus dados ficam no aparelho e podem ser sincronizados com sua família.</p><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="error">{error}</div>}<button className="primary" onClick={submit}>{signup?"Criar conta":"Entrar"}</button><button className="link" onClick={()=>setSignup(!signup)}>{signup?"Já tenho acesso":"Criar novo acesso"}</button></section></div>}
function Family({onSelect,onLogout}:{onSelect:(id:string)=>void;onLogout:()=>Promise<void>}){const [families,setFamilies]=useState<Array<{id:string;name:string;invite_code:string}>>([]),[name,setName]=useState(""),[code,setCode]=useState(""),[error,setError]=useState("");useEffect(()=>{listMyFamilies().then(setFamilies).catch(e=>setError(e.message));},[]);const create=async()=>{try{onSelect(await createFamily(name));}catch(e){setError(e instanceof Error?e.message:"Erro ao criar família");}};const join=async()=>{try{onSelect(await joinFamily(code));}catch(e){setError(e instanceof Error?e.message:"Erro ao entrar na família");}};return <div className="auth"><section className="auth-card"><span className="eyebrow">FAMÍLIA</span><h1>Escolha sua família</h1>{families.map(f=><button className="family" key={f.id} onClick={()=>onSelect(f.id)}><strong>{f.name}</strong><small>Código: {f.invite_code}</small></button>)}<input placeholder="Nome da nova família" value={name} onChange={e=>setName(e.target.value)}/><button className="primary" onClick={create}>Criar família</button><input placeholder="Código de convite" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button className="secondary" onClick={join}>Entrar com convite</button>{error&&<div className="error">{error}</div>}<button className="link" onClick={onLogout}>Sair</button></section></div>}

createRoot(document.getElementById("root")!).render(<StrictMode><App/></StrictMode>);
